name: Test

on: [push]

jobs:
  build-test:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-18.04]

    steps:
    - uses: actions/checkout@v1
    - name: install-blender
      run: |
        sudo add-apt-repository ppa:thomas-schiex/blender
        sudo apt-get update
        sudo apt-get install blender
    - name: test
      run: |
        blender ./tests/test-nodes.blend --background --python ./tests/test.py
        rm success
